baseurl = "/"
languageCode = "en-us"
title = "suwung"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "halaman awal"
    url = "/"
    weight = 1
[[menu.main]]
    name = "tentang ini"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "kategori"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "tag"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "rss feed"
    url = "/index.xml"

[params]
    description = "blog suwung"
    footer = "&copy; suwung.men 2018"
